# -*- coding: utf-8 -*-
"""Q3_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dWm-EWFDEwI15WbGIT0_bUIrxolF7Z1G
"""
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from linearRegression.linear_regression import LinearRegression
from os import path
import os

if not path.exists('Plots/Question3/'):
    os.makedirs('Plots/Question3/')

N=60
x = np.array([i*np.pi/180 for i in range(60,300,2)])
np.random.seed(10)
y = 3*x + 8 + np.random.normal(0,3,len(x)) 

y=pd.Series(y)
LR = LinearRegression(fit_intercept=True)
LR.fit_gradient_descent(pd.DataFrame(x), y, gradient_type='manual', penalty_type='l2', alpha=0.05, batch_size=40, num_iters=10, lr=0.01)

T_0, T_1 = [], []
for i in range(len(LR.all_coef)):
    T_0.append(LR.all_coef[i][0])
    T_1.append(LR.all_coef[i][1])

for i in range(10):
    fig = LR.plot_surface(pd.Series(x), y, LR.all_coef[i][0], LR.all_coef[i][1])
    fig.savefig('Plots/Question3/surface_plot'+str(i)+'.png')

fig = LR.plot_line_fit(pd.Series(x), y, LR.all_coef[0][0], LR.all_coef[0][1])
fig.savefig('Plots/Question3/plot_line_initial.png')

# fig.savefig('Plots/Question3/q3_1.png')
# fig = LR.plot_line_fit(pd.Series(x), y, LR.all_coef[5][0], LR.all_coef[5][1])
# fig.savefig('Plots/Question3/q3_2.png')
# fig = LR.plot_line_fit(pd.Series(x), y, LR.all_coef[10][0], LR.all_coef[10][1])
# fig.savefig('Plots/Question3/q3_3.png')
# fig = LR.plot_contour(pd.Series(x), y, LR.all_coef[0][0], LR.all_coef[0][1])
# fig.savefig('Plots/Question3/q3_4.png')
# fig = LR.plot_contour(pd.Series(x), y, LR.all_coef[5][0], LR.all_coef[5][1])
# fig.savefig('Plots/Question3/q3_5.png')
# fig = LR.plot_contour(pd.Series(x), y, LR.all_coef[10][0], LR.all_coef[10][1])
# fig.savefig('Plots/Question3/q3_6.png')


for i in range(10):
    fig = LR.plot_line_fit(pd.Series(x), y, LR.all_coef[i][0], LR.all_coef[i][1])
    fig.savefig('Plots/Question3/plot_line'+str(i)+'.png')

for i in range(10):
    fig = LR.plot_contour(pd.Series(x), y, LR.all_coef[i][0], LR.all_coef[i][1])
    fig.savefig('Plots/Question3/plot_contour'+str(i)+'.png')